import JSZip from "jszip";
import { saveAs } from "file-saver";

interface CodeFile {
    name: string;
    path?: string;
    content: string;
}

/**
 * Generate a ZIP file from generated code and trigger download
 */
export async function downloadCodeAsZip(
    projectName: string,
    files: CodeFile[],
    apiRoutes: { path: string; content: string }[],
    databaseSchema: string
): Promise<void> {
    const zip = new JSZip();

    // 1. Add Components
    const componentsFolder = zip.folder("components");
    if (componentsFolder) {
        files.forEach((file) => {
            componentsFolder.file(file.name, file.content);
        });
    }

    // 2. Add API Routes
    const apiFolder = zip.folder("app/api");
    if (apiFolder) {
        apiRoutes.forEach((route) => {
            // route.path might be 'app/api/auth/route.ts', we want to save relative to zip root
            zip.file(route.path, route.content);
        });
    }

    // 3. Add Prisma Schema
    const prismaFolder = zip.folder("prisma");
    if (prismaFolder) {
        prismaFolder.file("schema.prisma", databaseSchema);
    }

    // 4. Add Readme
    zip.file("README.md", `# ${projectName} - Generated by PixelForge AI

## Quick Start
1. Install dependencies: \`npm install\`
2. Set up database: \`npx prisma db push\`
3. Run dev server: \`npm run dev\`

Generated on: ${new Date().toLocaleString()}
`);

    // 5. Generate and save
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, `${projectName.toLowerCase().replace(/\s+/g, "-")}-export.zip`);
}

interface FigmaObject {
    type: string;
    left: number;
    top: number;
    width: number;
    height: number;
}

/**
 * Export canvas to Figma-compatible JSON (Conceptual)
 */
export function exportToFigma(canvasData: { objects: FigmaObject[] }) {
    const figmaJson = {
        document: {
            type: "DOCUMENT",
            children: [{
                type: "CANVAS",
                children: canvasData.objects.map((obj: FigmaObject) => ({
                    type: obj.type === 'textbox' ? 'TEXT' : 'RECTANGLE',
                    name: obj.type,
                    absoluteBoundingBox: { x: obj.left, y: obj.top, width: obj.width, height: obj.height },
                    fills: [{ type: "SOLID", color: { r: 0, g: 0, b: 0 } }] // Simplified
                }))
            }]
        }
    };
    const blob = new Blob([JSON.stringify(figmaJson, null, 2)], { type: "application/json" });
    saveAs(blob, "design-export-figma.json");
}

/**
 * Export canvas to Sketch-compatible JSON (Conceptual)
 */
export function exportToSketch() {
    // Similar to Figma but with Sketch properties
    const sketchJson = {
        _class: "document",
        pages: [{ _class: "page", name: "Page 1", layers: [] }]
    };
    const blob = new Blob([JSON.stringify(sketchJson, null, 2)], { type: "application/json" });
    saveAs(blob, "design-export-sketch.json");
}
